spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/carservice"
    username: carservice
    password: root # checking in passwords is bad, in production this would pull from secret manager or something