spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/carservice"
    username: carservice
    password: root # checking in passwords is bad, in production this would pull from secret manager or something
  flyway:
    enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always

---
spring:
  profiles: test
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
    database: default
    generate-ddl: true
  datasource:
    jdbc-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    hikari:
      connectionTimeout: 1000
      maximumPoolSize: 100
  jackson:
    time-zone: America/New_York